name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  no-deps:
    runs-on: macos-latest
    strategy:
      matrix:
        runNum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
