name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  no-deps:
    runs-on: windows-latest
    strategy:
      matrix:
        runNum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          verbose: true
      - name: Does codecov.exe exist?
        run: |
          if [[ -f D:\a\codecov-action\codecov-action\dist\codecov.exe ]]; then
            echo "it exists!"
          else
            echo "it does not exist"
          fi
